INSERT INTO CATEGORY (ID, NAME, ACTIVE) VALUES(1, 'Camisetas', true);
INSERT INTO CATEGORY (ID, NAME, ACTIVE) VALUES(2, 'Vasos', true);
INSERT INTO CATEGORY (ID, NAME, ACTIVE) VALUES(3, 'Juguetes', true);
INSERT INTO CATEGORY (ID, NAME, ACTIVE) VALUES(4, 'Accesorios Marvel', true);
INSERT INTO CATEGORY (ID, NAME, ACTIVE) VALUES(5, 'Accesorios DC', true);
